version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: projet_db_commune
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: projet_commune_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial
    #  maildev container
    maildev:
        image: maildev/maildev
        container_name: maildev_docker_soutenance
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - tutorial

    # Symfony apache project container
    www:
        build: docker/php
        container_name: projet_soutenance
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - tutorial

networks:
    tutorial:

volumes:
    db-data: